name: bcos
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pytorch-lightning[version='>=1.8']
  - torchmetrics
  - wandb
  - torchvision[version='>=0.14']
  - pytorch-cuda=11.6
  - ipython
  - matplotlib
  - jupyterlab
  - pytorch
  - cudnn=8.3
  - cudatoolkit=11.6
  - ca-certificates
  - certifi
  - openssl
  - rich
  - mamba
  - captum
  - einops
  - seaborn
  - pudb
  - tqdm
  - lime
  - scikit-image
  - timm
  - ipywidgets
  - pytest
  - pip:
    - cloudpickle==2.2.0
    - submitit==1.4.5
