# this is the environment used for producing the model results
# the `bcos` package should be compatible with pytorch 2.0 though
name: bcos
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch-lightning=1.8.1
  - torchmetrics=0.11
  - wandb
  - torchvision=0.14
  - pytorch-cuda=11.6
  - ipython
  - matplotlib
  - jupyterlab
  - pytorch=1.13
  - cudnn=8.3
  - cudatoolkit=11.6
  - ca-certificates
  - certifi
  - openssl
  - rich
  - mamba
  - captum=0.5
  - einops=0.6
  - seaborn
  - pudb
  - tqdm
  - lime=0.2.0.1
  - scikit-image=0.19.3
  - timm=0.6.12
  - ipywidgets
  - pytest
  - pip
  - pip:
    - cloudpickle==2.2.0
    - submitit==1.4.5
